### ISSUE TITLE
Request, prioritize allowed_filetypes in search

### ISSUE THREAD

**Issue by yroyathon** [mrusse/soularr#17]
This is a request and not a bug.  I've noticed when I have allowed_filetypes = flac,mp3, it will sometimes download flac and sometimes download mp3 for the same artist/album (I've had to stop and restart many times for other reasons).  Is there any way to prioritize the order of the items in allowed_filetypes as the priority?  I don't want ot use allowed_filetypes = flac and miss out on some albums.  I'd rather have an mp3 copy than no copy, but if both flac and mp3 exist then I'd prefer flac.

Is this difficult to add in the search logic?  Slskd's search order seems to be upload speed...  In a blue sky world, it would be nice to have 'cur_filetype, upload speed desc' as the order of search results processed, where cur_filetype is the first value in allowed_filetypes, then the 2nd, etc.

**Comment by mrusse** [comment]
These changes in allowed filetypes have been fixed with these commits https://github.com/mrusse/soularr/compare/9248e59044e0...b399c184eeda

Please take a look at this issue for more info on the further changes to allowed_filetypes: https://github.com/mrusse/soularr/issues/40

Have a good day and thank you for your help!!
