### ISSUE TITLE
number_of_albums_to_grab documentation is misleading

### ISSUE THREAD

**Issue by l2noob2** [mrusse/soularr#34]
#How mancy records to grab each run, must be a number between 1 - 2,147,483,647
number_of_albums_to_grab = 10

This is misleading since this actually refers to page size used when searching over a loop.

I would propose renaming this configuration variable to simply "page_size" to avoid confusion.

**Comment by mrusse** [comment]
I sortof agree but the number does equal to the number of albums the script will try to grab on each run so I would not say it is misleading. I do however have some updates coming that will make the functionality line up more with the name of the setting. I would also not change it either way since people are already using the setting and forcing them to change the naming would cause even more confusion...
