### ISSUE TITLE
Partial Album Downloads Removing Existing Songs

### ISSUE THREAD

**Issue by NovaCyntax** [mrusse/soularr#49]
**Scenario:**
I have songs 1 through 4 imported into Lidarr. Songs 6 through 10 are downloaded by Soularr. Upon import, songs 1 through 4 are automatically deleted, and songs 6 through 10 are imported. This appears to be cyclical, as the now-missing songs 1 through 4 will be downloaded and imported again, but songs 6 through 10 will be deleted again. 

"Complete" album downloads (which are most downloads) don't have any problems.

I'm not sure if this is an issue with Lidarr, Soularr, or my configuration options, but this does happen automatically in the background (which I was able to see via Lidarr's "history" tab). Ideally, songs should only ever be overwritten if a better quality is found, and outright deleted if manually initiated.

**Comment by mrusse** [comment]
Is this for one specific album? The way Lidarr and Soularr work is that they only look at what tracks are included in a given release. And when importing tracks anything that isnt part of the release will be deleated. This is on Lidarrs end. What is probably happening is it is picking a different release with "songs 6 through 10" and then the others are deleted because they are not part of the release. It would be helpful to know what album this is in reference too and see the Lidarr logs from the import. Again though this is a Lidarr issue most likely.

**Comment by NovaCyntax** [comment]
I will investigate more on Lidarr's end, perhaps it's always happened and I only just recently noticed. Thanks!
