### ISSUE TITLE
Typically only grabs partial of multi disc sets. 

### ISSUE THREAD

**Issue by neilanthonystuckey** [mrusse/soularr#50]
Is there a config option to help the script grab both CD1, CD2 etc of a release ? It seems more often then not i get only a single disc of a multi disc release. I tried setting allow_multi_disc = False delete and recreate container but seems to be doing the same. Thanks for this script/container i have been looking for this functionality for a long time.

**Comment by mrusse** [comment]
Sorry I didn't get to this sooner but allow_multi_disc needs to be True. Another thing to note is that search_for_tracks needs to be True as well. This is because the way it finds multi disc releases is basically treating each disc as an album itself and searching for a track from that "album". It can definitely be improved but grabbing multi disc releases does work with these settings.
