### ISSUE TITLE
Lidarr docker will not import music from soularr

### ISSUE THREAD

**Issue by BillButter** [mrusse/soularr#54]
Soularr is pulling from my wanted list correctly, and prompting slskd to download correctly.

However, once the download is complete Lidarr isn't getting it, meaning it isn't getting MusicBrainz metadata. 

In my lidarr docker
  lidarr:
    container_name: lidarr
    network_mode: "service:gluetun"
    image: youegraillot/lidarr-on-steroids 
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - ./lidarr/config:/config
      - ./lidarr/deemix:/config_deemix
      - /XboxDrives/Music/Lidarr:/music
      - /XboxDrives/Music/slskd/complete:/slskd

My config.ini
[Lidarr]
api_key = xxx
host_url = http://localhost:8686/lidarr
download_dir = /slskd/

**Comment by mrusse** [comment]
I will need to see your Lidarr debug logs at the time of a failed import. That will tell us the reason for the failure. It is usually due to a bad path setup or a permissions issue. Your paths look alright (althought I might remove the trailing slash from /slskd/) so I am leaning toward a permissions problem. Permissions issues are usually fixed by adding the SLSKD_UMASK env var to your Slskd docker compose. Try setting it to 000 to start.
