### ISSUE TITLE
Failures removed eagerly

### ISSUE THREAD

**Issue by lvleph** [mrusse/soularr#60]
I have been having an issue where an album's download will be removed because there was a file or files that failed to download. I have had many times where one file failed and all I needed to do is restart that file. Unfortunately, I am not always faster than soularr. I would much rather have the errored file to re-attempt the download or just let me manually deal with it. The offending code seems to be 
```python
                    # If we have errored files, cancel and remove ALL files so we can retry next time
                    if len(errored_files) > 0:
                        logger.error(f"FAILED: Username: {username} Directory: {dir['name']}")
                        cancel_and_delete(artist_folder['dir'], artist_folder['username'], directory["files"])
                        grab_list.remove(artist_folder)
                    elif len(pending_files) > 0:
                        unfinished += 1
```

Maybe an extra flag could be added to decide what to do?

**Comment by lvleph** [comment]
Maybe this is a bigger issue? I have noticed that an album isn't completely downloaded and soularr will try to import it.

**Comment by mrusse** [comment]
As you can see by the code you pointed to this is intended and a very useful feature. Soularr is meant to be set and forget. If an album has an errored track it will be removed. I'm not sure why that is so problem since it will be grabbed again on a future run through. As for it importing non complete albums, you have not provided much detail but either way an incomplete album will be rejected by Lidarr. If you have more info for this then please open a new issue.

**Comment by lvleph** [comment]
Imagine 1000 failures of a single album all sitting in `failed_imports`. That's a little extreme, but I've already witnessed 10 failures of the same album. Overall, i actually had everything. 

However, the other issue is more important and that is that soularr is attempting imports of incomplete album downloads. Then everything get place in `failed_imports`. I would definitely say that is unwanted behavior.

**Comment by mrusse** [comment]
Failed imports are meant to be manually cleared out every so often. It is already a planned feature to offer a setting to delete the files instead of placing them in failed imports, or delete the failed imports folder periodically. I have had soularr run through hundreds of artists and thousands of albums and I personally prefer how it handles the failed imports currently (and many other users have specifically requested it to work this way). You can't always please everyone I suppose. Thanks for your feedback. Have a good day.

**Comment by lvleph** [comment]
Maybe I should make another ticket, because I think the real issue is being closed over since this started as something more of a feature request and now has turned into a bug report. 

I will restate the issue...

An album is downloading and is not complete, and there are no errors, but soularr attempts to import the incomplete album.

**Comment by mrusse** [comment]
Yes I know you keep saying that but you will need to post another issue with more details and most importantly logs of this happening.
